### ISSUE TITLE
shared-lib-program example build order is wrong

### ISSUE THREAD

**Issue by ThakeeNathees** [SCons/scons-examples#5]
in the `shared-lib-program` example if I compile the lib with any name that lexicographically larger than `app` it compiles `app` first and `lib` next which took some time to understand why and I find out about **Requires()**.  could you add that in your example.

```python
DefaultEnvironment(tools=[])
env = Environment()

lib = env.SharedLibrary(
    target = 'lib',
    source = 'lib.c')
    
env.Program(
    target = 'app',
    source = 'app.c',
    LIBS=['lib'])
	
Requires(app, lib) ## <-- this is fix the build order

```

**Comment by bdbaddog** [comment]
Nope.. it should detect the dependency without `Requires`..

**Comment by bdbaddog** [comment]
@ThakeeNathees - what if you don't name the lib `lib` but say `abc` ?

**Comment by bdbaddog** [comment]
Here's the output I get when I name the shared library `lib`.. 

```
$ python ~/devel/scons/git/as_scons/scripts/scons.py
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o app.o -c app.c
gcc -o lib.os -c -fPIC lib.c
gcc -o lib.so  -shared   lib.os $( -L. $)
gcc -o app app.o -L.
app.o: In function `main':
app.c:(.text+0xf): undefined reference to `add'
collect2: error: ld returned 1 exit status
scons: *** [app] Error 1
scons: building terminated because of errors.

```
That's because SCons does some magic in removing the SHLIBPREFIX from the list libs before recreating and ends up removing it all together.


Here's the output if I name the library `abc`

```
$ python ~/devel/scons/git/as_scons/scripts/scons.py
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o libabc.so  -shared   lib.os $( -L. $)
gcc -o app app.o -L. -labc
scons: done building targets.
```
And if I name `xyz`

```
$ python ~/devel/scons/git/as_scons/scripts/scons.py
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o libxyz.so  -shared   lib.os $( -L. $)
gcc -o app app.o -L. -lxyz
scons: done building targets.

```

So there's nothing wrong with the example..

Just don't name your lib `lib`..
For further discussion come to the users mailing list, IRC channel, or preferably the [discord server ](https://discord.gg/bXVpWAy)

**Comment by bdbaddog** [comment]
@ThakeeNathees - can you file an issue for this on https://github.com/SCons/scons/issues. You can note that @bdbaddog  said to file it.

The issue is libname = 'lib'...

**Comment by mwichmann** [comment]
or more verbosely, if the lib name is the same as `$SHLIBPREFIX` then the name will be sliced down to an empty string. Which, umm, breaks stuff...
